sudo: required

language: java

jdk:
  - openjdk8

before_install:
  - chmod +x gradlew

script:
  - "./gradlew test"

branches:
  only:
    - master
    -
notifications:
  slack:
    secure: b/pwlcZC5lmfBUR5Otur5RzeUY6ZioE5432XalG3cfJZ/ePK70jw9PH5kuwjm65lSLPVyPyePQWJm+zu9F32UPNRi+podcu8ueVFG2n8KQenFG2aV8vhLZINghDZCLF3sDFEXHrmI9ZavF+4UgYGs+K/HOLQ5FBoAMoJSwuV0DAQYSm8ZrNXfTYOo/IpbUoK0ryK2Qf789zoHs5D9MZJ2DaiTnKEKDUsmILYj9lfMjBMVqwKRZgJtQK8go6OCTdZLEDx6ri4JU2lpFZh03fG3AFkhAcLMNDoBZfllG7QoKUmQ1qbmiHme8hNA1u00pndctOPgVrOivIXkUyU6vL3j9qo5qQLMYiySjiv1LSpr1sz+/d+4PTI2EF1EhgDh9RmvQXQAI9RXdkJYJAcqmJC4jkKPRD77g5pWp78aB5HikyrKNhqi8Rg3mPhp+RdzqB/lOOkF4QOx+wG5nucO8ZGEAaJ4XyoqmsUCObYsKMIux0QnyPCGtJoFZCUKIGURIdbsOwZPvuF1900cH5iJROArunqpkrMc3N/L9Ew7wabBfkDqjAssbrhr/03XHO8WQkd7HQdBqi28zf6/c/SE0OX6alxUSwRZWeVBhy48yrczKcChTeBpaqZGIhzGr6MqrCwCSKUTak0XBfWhuj8Z5HAUgW+O4jlmy3owUTdpGr/9Oc=
